name: e-commerce
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP and Apache2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          apache-modules: rewrite

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      - name: Install Symfony CLI
        run: |
          wget https://get.symfony.com/cli/installer -O - | bash
          export PATH="$HOME/.symfony/bin:$PATH"

      - name: Install Docker and Docker Compose
        uses: docker/setup-docker@v2

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Run Composer Install
        run: |
          composer install

      - name: Run Docker Compose Up
        run: |
          docker-compose up -d

      - name: Create Doctrine Database
        run: |
          bin/console doctrine:database:create -y

      - name: Run Doctrine Migrations
        run: |
          bin/console doctrine:migrations:migrate -y

      - name: Start Symfony Server
        run: |
          symfony server:start

